### ISSUE TITLE
Node 10

### ISSUE THREAD

**Issue by olistic** [yangshun/tree-node-cli#1]
Hello @yangshun, is Node 10 not supported? I just updated Docusaurus to v1.1.0, which uses this module, and my tests are failing because of Node 10 not being in the `engines` field of this package.

**Comment by yangshun** [comment]
Hey @olistic, Node 10 should be supported. It's my oversight. I'll fix it soon enough. Sorry about that!

**Comment by olistic** [comment]
No problem, want me to send a PR?

**Comment by yangshun** [comment]
Sure thing! Unfortunately I can't release a new version of `tree-node-cli` and `docusaurus` until I get off work (which is in a few hours time) though.
