### ISSUE TITLE
Too many parameters

### ISSUE THREAD

**Issue by haigopi** [yangshun/tree-node-cli#12]
>tree -L 2 -I
Too many parameters - 2

**Comment by yangshun** [comment]
![Huh wtf are you talking about](https://media.giphy.com/media/lkdH8FmImcGoylv3t3/source.gif)

**Comment by haigopi** [comment]
I thought you may understand it. Sorry!  When I am running this command "tree -L 2 -I dirName" on a windows machine, I see the error as "Too many parameters - 2."

**Comment by yangshun** [comment]
Your issue literally has two lines - no context, no steps to reproduce, no expected output no details. Not sure how I'm supposed to be understanding that. I recommend you read https://opensource.guide/how-to-contribute/

Unfortunately I don't have a Windows machine to test this on. @endiliey will you be able to help us out here?

**Comment by endiliey** [comment]
windows has in built tree command

**Comment by AdaWu-happy** [comment]
和windows内置的tree冲突了..

**Comment by yangshun** [comment]
> 和windows内置的tree冲突了..

@AdaWu-happy oh if that's the reason you can use `treee` instead.
