### ISSUE TITLE
incompatible with node <8.6.0

### ISSUE THREAD

**Issue by webOS101** [yangshun/tree-node-cli#3]
`tree.js` uses object spread, which is apparently not supported without a flag in node <8.6.0.  Could either replace with an `object.assign()` or transpile for publishing.

**Comment by yangshun** [comment]
@webOS101 Thanks, I'll fix it asap! May I know where/how you encountered this issue? Were you using Docusaurus?

**Comment by webOS101** [comment]
yes, that's where.  Trying to follow the setup guide and I had node 8.1

**Comment by yangshun** [comment]
I fixed it in 0401f7c. Could you see if it works for you?

**Comment by webOS101** [comment]
Sorry, I never got a chance to test this and it doesn't seem likely I will soon!  Didn't want to leave an open loop.
