### ISSUE TITLE
Add sort option

### ISSUE THREAD

**Issue by slorber** [yangshun/tree-node-cli#32]
Unfortunately the `fs.readdirSync(path);` ordering is not guaranteed across OS

I'm using Tree (node API) to create Jest snapshots of FS paths on Docusaurus, it works great 

But unfortunately, the tree order is non-deterministic and this leads to the CI failing but just on Windows: https://github.com/facebook/docusaurus/runs/5071012843?check_suite_focus=true

<img width="845" alt="image" src="https://user-images.githubusercontent.com/749374/152650645-0bb67616-745b-48e2-b690-c13c2f18856a.png">

Let me know if you can give me access on Git/npm @yangshun, I'd be happy to refresh a bit this package as there"s not a lot of good alternatives

**Comment by yangshun** [comment]
@slorber added you to the npm package! I'll add you to the repo as well.

**Comment by yangshun** [comment]
Implemented in #2c2db57. See if it fixes it for you. If it does should we bump a major/minor/patch? Could be considered both a breaking change and a bug fix

**Comment by slorber** [comment]
Thanks 👍 

I think it's safe to be considered as a windows bugfix because

>     -r, --reverse             Sort the output in reverse alphabetic order.

Implies not using the option is already sorted

And the test didn't change so the behavior is the same for most users

---

I'll add some basic typedefs and publish soon
