### ISSUE TITLE
scan list to save a file

### ISSUE THREAD

**Issue by yyman001** [yangshun/tree-node-cli#6]
scan list to save a file ?

**Comment by yangshun** [comment]
@yyman001 Sorry what do you mean?

**Comment by yyman001** [comment]
more convenient , thank!
I added a new file to implement it myself.

**Comment by yangshun** [comment]
@yyman001 Sorry I don't understand your messages. You could explain in Chinese if it's easier. I'd love to improve this library if you have suggestions.

**Comment by Little-Fan** [comment]
他的意思是,怎么样把命令行的的树结构目录,生成在一个文件里.

**Comment by yangshun** [comment]
原来如此。这功能其实不需要设在这package里。用`>`就可以把命令行打印出来的东西存金文件了。

比如：

```
$ tree -L 2 -I "node_modules" > myfile.txt
```
